import React, { useState } from 'react';
import MyVerticallyCenteredModal1 from "./Function";
import i1 from './Image/work/coronation_dehradun.jpg' ;
import i2 from './Image/work/ranikhet_almora.jpg' ;
import i3 from './Image/work/coronation_dehradun.jpg' ;
import i4 from './Image/work/coronation_dehradun.jpg' ;
import i5 from './Image/work/coronation_dehradun.jpg' ;
import i6 from './Image/work/coronation_dehradun.jpg' ;
import i7 from './Image/work/coronation_dehradun.jpg' ;
import i8 from './Image/work/coronation_dehradun.jpg' ;
import i9 from './Image/work/coronation_dehradun.jpg' ;
import i10 from './Image/work/coronation_dehradun.jpg' ;
import i11 from './Image/work/coronation_dehradun.jpg' ;
import i12 from './Image/work/coronation_dehradun.jpg' ;
import i13 from './Image/work/coronation_dehradun.jpg' ;
import i14 from './Image/work/coronation_dehradun.jpg' ;
import i15 from './Image/work/coronation_dehradun.jpg' ;
import i16 from './Image/work/coronation_dehradun.jpg' ;

import { MDBDataTable } from 'mdbreact';
import { MDBTable, MDBTableBody, MDBTableHead } from 'mdbreact';

const DatatablePage = () => {
const [modalShow1, setModalShow1] = React.useState(false);
  const data = {
    columns: [
        {
                label: 'Sr. No.',
                field: 'serial',
                sort: 'desc',
                width: 40
              },{
                label: 'FMR code',
                field: 'fmr',
                sort: 'desc',
                width: 60
              },
      {
        label: 'Name of work',
        field: 'name',
        sort: 'asc',
        width: 150
      },
      {
        label: 'District',
        field: 'district',
        sort: 'asc',
        width: 90
      },
      {
        label: 'Executing Agency',
        field: 'executing',
        sort: 'asc',
        width: 100
      },
      {
        label: 'Sanctioned Year',
        field: 'sanctioned',
        sort: 'asc',
        width: 110
      },{
        label: 'MoU Signed with EA',
        field: 'mou',
        sort: 'asc',
        width: 100
      },
      {
        label: 'Approved Project Cost',
        field: 'cost',
        sort: 'asc',
        width: 100
      },
      {
        label: 'Recieved fund from GOI',
        field: 'goi',
        sort: 'asc',
        width: 120
      },{
        label: 'Balance to recieve from GOI',
        field: 'bgoi',
        sort: 'asc',
        width: 120
      },
      {
        label: 'Amount released to EA',
        field: 'released',
        sort: 'asc',
        width: 120
      },
      {
        label: 'Amount Expenditure by EA',
        field: 'expenditure',
        sort: 'asc',
        width: 120
      },{
        label: 'Balance Amount to be released to EA',
        field: 'bea',
        sort: 'asc',
        width: 120
      },{
        label: 'Utilization Certificate',
        field: 'uc',
        sort: 'asc',
        width: 120
      },
      {
        label: 'Physical Progress in %',
        field: 'pp',
        sort: 'asc',
        width: 120
      },
      {
        label: 'Date of Start',
        field: 'start',
        sort: 'asc',
        width: 120
      },
      {
        label: 'Date of completion',
        field: 'complete',
        sort: 'asc',
        width: 120
      },
      {
        label: 'Expected/Actual Date of Start',
        field: 'eacomplete',
        sort: 'asc',
        width: 160
      },
      {
        label: 'Hand Over',
        field: 'ho',
        sort: 'asc',
        width: 120
      },
      {
        label: 'Photographs',
        field: 'img',
        sort: 'asc',
        width: 120
      },
      {
        label: 'Location',
        field: 'location',
        sort: 'asc',
        width: 100
      },
      {
        label: 'Remarks',
        field: 'remark',
        sort: 'asc',
        width: 120
      },
      {
        label: 'Edit',
        field: 'edit',
        sort: 'asc',
        width: 70
      }
    ],
    rows: [
      
{
        serial:38,
        fmr: 67,
        mou:"hello",
        bgoi:"yy",
bea:"yy",
uc:"yy",
pp:"yy",
start:"yy",
complete:"yy",
eacomplete:"yy",
ho:"yy",
remark:"yy",
name:"Construction of  Day Care PHC, Mo transit hostal at jankichatty , District Uttarkashi. ",
district:"Uttarakashi",
executing:"Rural Works Department",
sanctioned:"2018-19 approved amt 4162",
cost:316.00,
goi:3901.15,
released:3679,
expenditure:3679,
img:<a href="#"><i className="fas fa-images fa-2x"></i></a>,
location:<a href="https://www.google.com/maps/dir//languagezone/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x39092b517c7e581b:0x2f036815b6f90e48?sa=X&ved=2ahUKEwj0jofN1qPxAhWr8HMBHSW7CbgQ9RcwE3oECDAQBA"><i className="fas fa-map-marked-alt fa-2x"></i></a>,
edit:<i class="fas fa-edit fa-2x"></i>     
      },{
        fmr: 67,
        mou:"hello",
        bgoi:"yy",
bea:"yy",
uc:"yy",
pp:"yy",
start:"yy",
complete:"yy",
eacomplete:"yy",
ho:"yy",
remark:"yy",
        serial:37,
name:"MO Transit Hostel 8 units, CHC Purola",
district:"Uttarakashi",
executing:"PeyJal Nigam",
sanctioned:"2018-19 approved amt 4162",
cost:264.28,
goi:3901.15,
released:3679,
expenditure:3679,
img:<a href="#"><i className="fas fa-images fa-2x"></i></a>,
location:<a href="https://www.google.com/maps/dir//languagezone/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x39092b517c7e581b:0x2f036815b6f90e48?sa=X&ved=2ahUKEwj0jofN1qPxAhWr8HMBHSW7CbgQ9RcwE3oECDAQBA"><i className="fas fa-map-marked-alt fa-2x"></i></a>,
edit:<i class="fas fa-edit fa-2x"></i>     
      },{
        fmr: 67,
        mou:"hello",
        bgoi:"yy",
bea:"yy",
uc:"yy",
pp:"yy",
start:"yy",
complete:"yy",
eacomplete:"yy",
ho:"yy",
remark:"yy",
        serial:36,
name:"MO Transit Hostel 8 units, CHC Naugaon",
district:"Uttarakashi",
executing:"PeyJal Nigam",
sanctioned:"2018-19 approved amt 4162",
cost:264.34,
goi:3901.15,
released:3679,
expenditure:3679,
img:<a href="#"><i className="fas fa-images fa-2x"></i></a>,
location:<a href="https://www.google.com/maps/dir//languagezone/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x39092b517c7e581b:0x2f036815b6f90e48?sa=X&ved=2ahUKEwj0jofN1qPxAhWr8HMBHSW7CbgQ9RcwE3oECDAQBA"><i className="fas fa-map-marked-alt fa-2x"></i></a>,
edit:<i class="fas fa-edit fa-2x"></i>     
      },{fmr: "",
        mou:"",
        bgoi:"-",
bea:"34.99",
uc:"Yes",
pp:83,
start:"March-17",
complete:"March-21",
eacomplete:"",
ho:"",
remark:"Work is in Progress. One Block completed , IInd is in 90% , II rd is in 75% . 1276.89 Alloted to  CMO PAURI and CMO retain  35.40 lakh and 1241.90 lakh alloted to agency",
        serial:35,
name:"30 MO Residence at Kotdwar",
district:"Pauri",
executing:"UPRNN",
sanctioned:"2018-19 approved amt 4162",
cost:1276.89,
goi:1276.89,
released:1241.9,
expenditure:1165.1,
img:<a href=""><i className="fas fa-images fa-2x"></i></a>,
location:<a href="https://www.google.com/maps/dir//languagezone/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x39092b517c7e581b:0x2f036815b6f90e48?sa=X&ved=2ahUKEwj0jofN1qPxAhWr8HMBHSW7CbgQ9RcwE3oECDAQBA"><i className="fas fa-map-marked-alt fa-2x"></i></a>,
edit:<i class="fas fa-edit fa-2x"></i>     
      },{fmr: "",
        mou:"",
        bgoi:"-",
bea:"-",
uc:"Yes CMO",
pp:100,
start:"Sep-19",
complete:"Dec-20",
eacomplete:"March-21",
ho:"In Progress",
remark:"",
        serial:34,
name:"DEIC, DH Rudrapur",
district:"US Nagar",
executing:"BRIDCUL",
sanctioned:"2020-21 approved amt 4162",
cost:155.88,
goi:155.88,
released:155.88,
expenditure:140.00,
img:<a href="#"><i className="fas fa-images fa-2x"></i></a>,
location:<a href="https://www.google.com/maps/dir//languagezone/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x39092b517c7e581b:0x2f036815b6f90e48?sa=X&ved=2ahUKEwj0jofN1qPxAhWr8HMBHSW7CbgQ9RcwE3oECDAQBA"><i className="fas fa-map-marked-alt fa-2x"></i></a>,
edit:<i class="fas fa-edit fa-2x"></i>     
      },{fmr: "",
      mou:"",
      bgoi:"-",
bea:"-",
uc:"Yes",
pp:"100%",
start:"sep-19",
complete:"April-20",
eacomplete:"March-21",
ho:"",
remark:"Handed over to CMO/CMS",
        serial:33,
name:"MO Transit Hostel 8 units, CHC Purola",
district:"Uttarkashi",
executing:"PeyJal Nigam",
sanctioned:"2018-19 approved amt 4162",
cost:264.28,
goi:264.28,
released:264.28,
expenditure:234.34,
img:<a href="#"><i className="fas fa-images fa-2x"></i></a>,
location:<a href="https://www.google.com/maps/dir//languagezone/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x39092b517c7e581b:0x2f036815b6f90e48?sa=X&ved=2ahUKEwj0jofN1qPxAhWr8HMBHSW7CbgQ9RcwE3oECDAQBA"><i className="fas fa-map-marked-alt fa-2x"></i></a>,
edit:<i class="fas fa-edit fa-2x"></i>     
      },{fmr: "",
        mou:"",
        bgoi:"-",
bea:"-",
uc:"Yes",
pp:"100%",
start:"sep-19",
complete:"April-20",
eacomplete:"March-21",
ho:"",
remark:"Handed over to CMO/CMS",
        serial:32,
name:"MO Transit Hostel 8 units, CHC Naugaon",
district:"Uttarkashi",
executing:"PeyJal Nigam",
sanctioned:"2018-19 approved amt 4162",
cost:264.34,
goi:264.34,
released:264.34,
expenditure:232.16,
img:<a href=""><i className="fas fa-images fa-2x"></i></a>,
location:<a href="https://www.google.com/maps/dir//languagezone/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x39092b517c7e581b:0x2f036815b6f90e48?sa=X&ved=2ahUKEwj0jofN1qPxAhWr8HMBHSW7CbgQ9RcwE3oECDAQBA"><i className="fas fa-map-marked-alt fa-2x"></i></a>,
edit:<i class="fas fa-edit fa-2x"></i>     
      },{fmr: "",
        mou:"",
        bgoi:"",
bea:"",
uc:"Yes",
pp:"60%",
start:"Nov-19",
complete:"April-21",
eacomplete:"June-21",
ho:"",
remark:"Only Furniture Procurement remaining",
        serial:31,
name:"MO Transit Hostel 12 units, SDH Khatima",
district:"U S Nagar",
executing:"PeyJal Nigam",
sanctioned:"2019-20 approved amt 4162",
cost:269.22,
goi:269.22,
released:269.22,
expenditure:100.00,
img:<a href="#"><i className="fas fa-images fa-2x"></i></a>,
location:<a href="https://www.google.com/maps/dir//languagezone/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x39092b517c7e581b:0x2f036815b6f90e48?sa=X&ved=2ahUKEwj0jofN1qPxAhWr8HMBHSW7CbgQ9RcwE3oECDAQBA"><i className="fas fa-map-marked-alt fa-2x"></i></a>,
edit:<i class="fas fa-edit fa-2x"></i>     
      },{fmr: "",
      mou:"",
      bgoi:"-",
bea:"-",
uc:"yes",
pp:"98%",
start:"March-19",
complete:"April-20",
eacomplete:"March-21",
ho:"",
remark:"Only Furniture Procurement remaining",
        serial:30,
name:"MO Transit Hostel 8 units, CHC Lambgaon",
district:"Tehri",
executing:"Rural Works Department",
sanctioned:"2018-19 approved amt 4162",
cost:269.16,
goi:269.16,
released:269.16,
expenditure:198.34,
img:<a href="#"><i className="fas fa-images fa-2x"></i></a>,
location:<a href="https://www.google.com/maps/dir//languagezone/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x39092b517c7e581b:0x2f036815b6f90e48?sa=X&ved=2ahUKEwj0jofN1qPxAhWr8HMBHSW7CbgQ9RcwE3oECDAQBA"><i className="fas fa-map-marked-alt fa-2x"></i></a>,
edit:<i class="fas fa-edit fa-2x"></i>     
      },{fmr: "",
      mou:"",
      bgoi:"-",
bea:"-",
uc:"yes",
pp:"60%",
start:"March-19",
complete:"April-20",
eacomplete:"Nov-21",
ho:"",
remark:"Change of location from baijnath to Cham. Work is in progress",
        serial:29,
name:"MO Transit Hostel 8 units, CHC Cham ",
district:"Tehri",
executing:"Rural Works Department",
sanctioned:"2018-19 approved amt 4162",
cost:248.02,
goi:248.02,
released:248.02,
expenditure:122.22,
img:<a href="#"><i className="fas fa-images fa-2x"></i></a>,
location:<a href="https://www.google.com/maps/dir//languagezone/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x39092b517c7e581b:0x2f036815b6f90e48?sa=X&ved=2ahUKEwj0jofN1qPxAhWr8HMBHSW7CbgQ9RcwE3oECDAQBA"><i className="fas fa-map-marked-alt fa-2x"></i></a>,
edit:<i class="fas fa-edit fa-2x"></i>     
      },{fmr: "",
        mou:"",
        bgoi:"-",
bea:"-",
uc:"yes",
pp:"95%",
start:"March-19",
complete:"April-20",
eacomplete:"March-21",
ho:"",
remark:"Only Furniture Procurement remaining",
serial:28,
name:"MO Transit Hostel 8 units, CHC Agastyamuni",
district:"Rudraprayag",
executing:"Pey Jal Nigam",
sanctioned:"2018-19 approved amt 4162",
cost:251.6,
goi:251.6,
released:251.6,
expenditure:240.40,
img:<a href="#"><i className="fas fa-images fa-2x"></i></a>,
location:<a href="https://www.google.com/maps/dir//languagezone/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x39092b517c7e581b:0x2f036815b6f90e48?sa=X&ved=2ahUKEwj0jofN1qPxAhWr8HMBHSW7CbgQ9RcwE3oECDAQBA"><i className="fas fa-map-marked-alt fa-2x"></i></a>,
edit:<i class="fas fa-edit fa-2x"></i>     
      },{fmr: "",
      mou:"",
      bgoi:"",
bea:"",
uc:"Yes",
pp:"35%",
start:"March-19",
complete:"April-20",
eacomplete:"Dec-21",
ho:"",
remark:"Change of location from Gangolihat to Didihat approved. GF & FF work is in progress ",
        serial:27,
name:"MO Transit Hostel 8 units, CHC Berinag",
district:"Pithoragarh",
executing:"PeyJal Nigam",
sanctioned:"2018-19 approved amt 4162",
cost:240.93,
goi:240.93,
released:240.93,
expenditure:128.29,
img:<a href="#"><i className="fas fa-images fa-2x"></i></a>,
location:<a href="https://www.google.com/maps/dir//languagezone/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x39092b517c7e581b:0x2f036815b6f90e48?sa=X&ved=2ahUKEwj0jofN1qPxAhWr8HMBHSW7CbgQ9RcwE3oECDAQBA"><i className="fas fa-map-marked-alt fa-2x"></i></a>,
edit:<i class="fas fa-edit fa-2x"></i>     
      },{fmr: "",
      mou:"",
      bgoi:"",
bea:"",
uc:"Yes",
pp:"90%",
start:"Aug-19",
complete:"April-20",
eacomplete:"March-21",
ho:"",
remark:"Finishing work is in progress",
        serial:26,
name:"MO Transit Hostel 8 units, CHC Didihat",
district:"Pithoragarh",
executing:"PeyJal Nigam",
sanctioned:"2018-19 approved amt 4162",
cost:262.04,
goi:262.04,
released:262.04,
expenditure:182.62,
img:<a href="#"><i className="fas fa-images fa-2x"></i></a>,
location:<a href="https://www.google.com/maps/dir//languagezone/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x39092b517c7e581b:0x2f036815b6f90e48?sa=X&ved=2ahUKEwj0jofN1qPxAhWr8HMBHSW7CbgQ9RcwE3oECDAQBA"><i className="fas fa-map-marked-alt fa-2x"></i></a>,
edit:<i class="fas fa-edit fa-2x"></i>     
      },{fmr: 67,
        mou:"hello",
        bgoi:"yy",
bea:"yy",
uc:"yy",
pp:"yy",
start:"yy",
complete:"yy",
eacomplete:"yy",
ho:"yy",
remark:"yy",
        serial:25,
name:"30 MO Residence at Kotdwar",
district:"Pauri",
executing:"UPRNN",
sanctioned:"2018-19 approved amt 4162",
cost:1276.89,
goi:3901.15,
released:3679,
expenditure:3679,
img:<a href=""><i className="fas fa-images fa-2x"></i></a>,
location:<a href="https://www.google.com/maps/dir//languagezone/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x39092b517c7e581b:0x2f036815b6f90e48?sa=X&ved=2ahUKEwj0jofN1qPxAhWr8HMBHSW7CbgQ9RcwE3oECDAQBA"><i className="fas fa-map-marked-alt fa-2x"></i></a>,
edit:<i class="fas fa-edit fa-2x"></i>     
      },{fmr: "",
      mou:"",
      bgoi:"",
bea:"10.00",
uc:"Yes",
pp:"98%",
start:"March-19",
complete:"April-20",
eacomplete:"March-21",
ho:"",
remark:"Finishing work is in progress",
        serial:24,
name:"MO Transit Hostel 12 units, District Hospital",
district:"Pauri",
executing:"PeyJal Nigam",
sanctioned:"2018-19 approved amt 4162",
cost:328.59,
goi:328.59,
released:318.59,
expenditure:273.16,
img:<a href="#"><i className="fas fa-images fa-2x"></i></a>,
location:<a href="https://www.google.com/maps/dir//languagezone/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x39092b517c7e581b:0x2f036815b6f90e48?sa=X&ved=2ahUKEwj0jofN1qPxAhWr8HMBHSW7CbgQ9RcwE3oECDAQBA"><i className="fas fa-map-marked-alt fa-2x"></i></a>,
edit:<i class="fas fa-edit fa-2x"></i>     
      },{fmr: "",
        mou:"",
        bgoi:"",
bea:"",
uc:"Yes",
pp:"100%",
start:"March-19",
complete:"April-20",
eacomplete:"March-21",
ho:"",
remark:"Only Furniture Procurement remaining",
        serial:23,
name:"MO Transit Hostel 8 units, Thailisain,  DH ",
district:"Pauri",
executing:"PeyJal Nigam",
sanctioned:"2018-19 approved amt 4162",
cost:254.78,
goi:254.78,
released:254.78,
expenditure:254.78,
img:<a href="#"><i className="fas fa-images fa-2x"></i></a>,
location:<a href="https://www.google.com/maps/dir//languagezone/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x39092b517c7e581b:0x2f036815b6f90e48?sa=X&ved=2ahUKEwj0jofN1qPxAhWr8HMBHSW7CbgQ9RcwE3oECDAQBA"><i className="fas fa-map-marked-alt fa-2x"></i></a>,
edit:<i class="fas fa-edit fa-2x"></i>     
      },{fmr: "",
      mou:"",
      bgoi:"494.27",
bea:"1304.27",
uc:"",
pp:"",
start:"",
complete:"",
eacomplete:"",
ho:"",
remark:" ",
        serial:22,
name:"50 Bedded MCH wing in Sub District Female Hospital, Haldwani ",
district:"Nanital",
executing:"PeyJal Nigam",
sanctioned:"2020-21 approved amt 4162",
cost:1304.27,
goi:810.00,
released:"",
expenditure:"",
img:<a href="#"><i className="fas fa-images fa-2x"></i></a>,
location:<a href="https://www.google.com/maps/dir//languagezone/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x39092b517c7e581b:0x2f036815b6f90e48?sa=X&ved=2ahUKEwj0jofN1qPxAhWr8HMBHSW7CbgQ9RcwE3oECDAQBA"><i className="fas fa-map-marked-alt fa-2x"></i></a>,
edit:<i class="fas fa-edit fa-2x"></i>     
      },{fmr: "",
      mou:"",
      bgoi:"3837.51",
bea:"6337.51",
uc:"",
pp:"",
start:"",
complete:"",
eacomplete:"",
ho:"",
remark:" ",
        serial:21,
name:"Multispecialty 200 bedded hospital  in Haldwani ",
district:"Nanital",
executing:"PeyJal Nigam",
sanctioned:"2020-21 approved amt 4162",
cost:7337.51,
goi:3500.00,
released:1000.00,
expenditure:"",
img:<a href="#"><i className="fas fa-images fa-2x"></i></a>,
location:<a href="https://www.google.com/maps/dir//languagezone/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x39092b517c7e581b:0x2f036815b6f90e48?sa=X&ved=2ahUKEwj0jofN1qPxAhWr8HMBHSW7CbgQ9RcwE3oECDAQBA"><i className="fas fa-map-marked-alt fa-2x"></i></a>,
edit:<i class="fas fa-edit fa-2x"></i>     
      },{fmr: "",
      mou:"",
      bgoi:"",
bea:"",
uc:"Yes",
pp:"80%",
start:"Aug-19",
complete:"April-20",
eacomplete:"May-21",
ho:"",
remark:"Electrical, & finishing work is in progress  ",
        serial:20,
name:"MO Transit Hostel 8 units, CHC Ramgarh",
district:"Nanital",
executing:"PeyJal Nigam",
sanctioned:"2018-19 approved amt 4162",
cost:240.33 ,
goi:240.33,
released:240.33,
expenditure:150.00,
img:<a href="#"><i className="fas fa-images fa-2x"></i></a>,
location:<a href="https://www.google.com/maps/dir//languagezone/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x39092b517c7e581b:0x2f036815b6f90e48?sa=X&ved=2ahUKEwj0jofN1qPxAhWr8HMBHSW7CbgQ9RcwE3oECDAQBA"><i className="fas fa-map-marked-alt fa-2x"></i></a>,
edit:<i class="fas fa-edit fa-2x"></i>     
      },{fmr: "",
        mou:"",
        bgoi:"",
bea:"",
uc:"Yes",
pp:"100%",
start:"Aug-19",
complete:"April-20",
eacomplete:"May-21",
ho:"",
remark:"Only Furniture Procurement remaining",
        serial:19,
name:"MO Transit Hostel 8 units, CHC Betalghat",
district:"Nanital",
executing:"PeyJal Nigam",
sanctioned:"2018-19 approved amt 4162",
cost:225.11,
goi:225.11,
released:225.11,
expenditure:205.11,
img:<a href="#"><i className="fas fa-images fa-2x"></i></a>,
location:<a href="https://www.google.com/maps/dir//languagezone/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x39092b517c7e581b:0x2f036815b6f90e48?sa=X&ved=2ahUKEwj0jofN1qPxAhWr8HMBHSW7CbgQ9RcwE3oECDAQBA"><i className="fas fa-map-marked-alt fa-2x"></i></a>,
edit:<i class="fas fa-edit fa-2x"></i>     
      },{fmr: "",
        mou:"",
        bgoi:287.00,
bea:987.00,
uc:"",
pp:"",
start:"",
complete:"",
eacomplete:"",
ho:"",
remark:"",
        serial:18,
name:"UCHC Bhupatwala ",
district:"Haridwar",
executing:"BRIDCUL",
sanctioned:"2018-19 approved amt 4162",
cost:987.00,
goi:700.15,
released:"-",
expenditure:"-",
img:<a href="#"><i className="fas fa-images fa-2x"></i></a>,
location:<a href="https://www.google.com/maps/dir//languagezone/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x39092b517c7e581b:0x2f036815b6f90e48?sa=X&ved=2ahUKEwj0jofN1qPxAhWr8HMBHSW7CbgQ9RcwE3oECDAQBA"><i className="fas fa-map-marked-alt fa-2x"></i></a>,
edit:<i class="fas fa-edit fa-2x"></i>     
      },{fmr: "",
        mou:"",
        bgoi:885.81,
bea:3185.81,
uc:"",
pp:0,
start:"Dec-20",
complete:"Nov-22",
eacomplete:"Nov-22",
ho:"",
remark:"Contract Awarded to Shri Ji Kripa Buildcon Ltd, Demolition  of old Building  work started",
        serial:17,
name:"MCH Wing, 200 bedded Haridwar",
district:"Haridwar",
executing:"PeyJal Nigam",
sanctioned:"2019-20 approved amt 4162",
cost:3885.81,
goi:3000.00,
released:700.00,
expenditure:"",
img:<a href="#"><i className="fas fa-images fa-2x"></i></a>,
location:<a href="https://www.google.com/maps/dir//languagezone/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x39092b517c7e581b:0x2f036815b6f90e48?sa=X&ved=2ahUKEwj0jofN1qPxAhWr8HMBHSW7CbgQ9RcwE3oECDAQBA"><i className="fas fa-map-marked-alt fa-2x"></i></a>,
edit:<i class="fas fa-edit fa-2x"></i>     
      },{fmr: "",
        mou:"",
        bgoi:150.00,
bea:250.00,
uc:"",
pp:"",
start:"",
complete:"",
eacomplete:"",
ho:"",
remark:"TAC Awaited",
        serial:16,
name:"Construction of 'District Centre of Excellence' blood bank for Dehradun. ",
district:"Dehradun",
executing:"Mandi Parishad",
sanctioned:"2020-21 approved amt 4162",
cost:250.00,
goi:100.00,
released:"",
expenditure:"",
img:<a href="#"><i className="fas fa-images fa-2x"></i></a>,
location:<a href="https://www.google.com/maps/dir//languagezone/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x39092b517c7e581b:0x2f036815b6f90e48?sa=X&ved=2ahUKEwj0jofN1qPxAhWr8HMBHSW7CbgQ9RcwE3oECDAQBA"><i className="fas fa-map-marked-alt fa-2x"></i></a>,
edit:<i class="fas fa-edit fa-2x"></i>     
      },{fmr: "",
        mou:"",
        bgoi:"",
bea:177.00,
uc:"",
pp:"",
start:"",
complete:"",
eacomplete:"",
ho:"",
remark:"TAC Awaited",
        serial:15,
name:"Construction of RNTCP lab at dehradun",
district:"Dehradun",
executing:"Mandi Parishad",
sanctioned:"2020-21 approved amt 4162",
cost:177.00,
goi:177.00,
released:"",
expenditure:"",
img:<a href="#"><i className="fas fa-images fa-2x"></i></a>,
location:<a href="https://www.google.com/maps/dir//languagezone/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x39092b517c7e581b:0x2f036815b6f90e48?sa=X&ved=2ahUKEwj0jofN1qPxAhWr8HMBHSW7CbgQ9RcwE3oECDAQBA"><i className="fas fa-map-marked-alt fa-2x"></i></a>,
edit:<i class="fas fa-edit fa-2x"></i>     
      },{fmr: 67,
        mou:"hello",
        bgoi:"yy",
bea:"yy",
uc:"yy",
pp:"yy",
start:"yy",
complete:"yy",
eacomplete:"yy",
ho:"yy",
remark:"yy",
        serial:14,
name:"Construction of corridor for connecting old building to new building  of Coronation Hospital ",
district:"Dehradun",
executing:"PeyJal Nigam",
sanctioned:"2018-19 approved amt 4162",
cost:188.70,
goi:3901.15,
released:3679,
expenditure:3679,
img:<a href=""><i className="fas fa-images fa-2x"></i></a>,
location:<a href="https://www.google.com/maps/dir//languagezone/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x39092b517c7e581b:0x2f036815b6f90e48?sa=X&ved=2ahUKEwj0jofN1qPxAhWr8HMBHSW7CbgQ9RcwE3oECDAQBA"><i className="fas fa-map-marked-alt fa-2x"></i></a>,
edit:<i class="fas fa-edit fa-2x"></i>     
      },{fmr: "" ,
      mou:" ",
      bgoi:"1760.00",
      bea:"8760.00",
      uc:"Yes",
      pp:5,
      start:"June-19",
      complete:"Dec-20",
      eacomplete:"June-22",
      ho:"Yes",
remark:"Foundation work is in progress",
        serial:13,
name:"300 Bed Hospital, Harrawala",
district:"Dehradun",
executing:"Bridge & Roof",
sanctioned:"2018-19 approved amt 4162",
cost:9760.00,
goi:8000.00,
released:1000.00,
expenditure:820.00,
img:<a href="#"><i className="fas fa-images fa-2x"></i></a>,
location:<a href="https://www.google.com/maps/dir//languagezone/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x39092b517c7e581b:0x2f036815b6f90e48?sa=X&ved=2ahUKEwj0jofN1qPxAhWr8HMBHSW7CbgQ9RcwE3oECDAQBA"><i className="fas fa-map-marked-alt fa-2x"></i></a>,
edit:<i class="fas fa-edit fa-2x"></i>     
      }, {fmr: "" ,
      mou:" ",
      bgoi:"-",
      bea:"",
      uc:"Yes",
      pp:100,
      start:"June-19",
      complete:"Dec-20",
      eacomplete:"Mar-21",
      ho:"Yes",
remark:"Handing Taking Over Process",
        serial:12,
name:"100 Bed Hospital, Coronation Hospital",
district:"Dehradun",
executing:"Pey Jal Nigam",
sanctioned:"2018-19 approved amt 4162",
cost:3901.15,
goi:3901.15,
released:3901.15,
expenditure:3679.00,
img:<a href={i1} target="_blank"><i className="fas fa-images fa-2x"></i></a>,
location:<i className="fas fa-map-marked-alt fa-2x"></i>,
edit:<i class="fas fa-edit fa-2x"></i>             
      },
      {fmr: "" ,
      mou:" ",
      bgoi:"-",
      bea:"10.00",
      uc:"Yes",
      pp:70,
      start:"March-19",
      complete:"April-20",
      eacomplete:"Aug-21",
      ho:"",
remark:"Electrical, Plumbing & flooring work is in progress  ",
        serial:11,
name:"MO Transit Hostel 12 units, DH ",
district:"Champawat",
executing:"Pey Jal Nigam",
sanctioned:"2018-19 approved amt 4162",
cost:288.27,
goi:288.27,
released:278.27,
expenditure:177.02,
img:<i className="fas fa-images fa-2x"></i>,
location:<i className="fas fa-map-marked-alt fa-2x"></i>,
edit:<i class="fas fa-edit fa-2x"></i>             
      },
      {fmr: "" ,
      mou:" ",
      bgoi:"-",
      bea:"-",
      uc:"Yes",
      pp:80,
      start:"March-19",
      complete:"April-20",
      eacomplete:"June-21",
      ho:"",
remark:"Electrical, & finishing work is in progress",
        serial:10,
name:"MO Transit Hostel 8 units, CHC Pati",
district:"Champawat",
executing:"Pey Jal Nigam",
sanctioned:"2018-19 approved amt 4162",
cost:233.24,
goi:233.24,
released:233.24,
expenditure:155.59,
img:<i className="fas fa-images fa-2x"></i>,
location:<i className="fas fa-map-marked-alt fa-2x"></i>,
edit:<i class="fas fa-edit fa-2x"></i>             
      },
      {fmr: "" ,
      mou:" ",
      bgoi:"-",
      bea:"-",
      uc:"Yes",
      pp:40,
      start:"March-19",
      complete:"April-20",
      eacomplete:"Dec-21",
      ho:"",
remark:"Slab 1st & 2nd Floor casted. Work is in progress",
        serial:9,
name:"MO Transit Hostel 8 units,CHC Gairsain",
district:"Chamoli",
executing:"Pey Jal Nigam",
sanctioned:"2018-19 approved amt 4162",
cost:263.72,
goi:263.72,
released:263.72,
expenditure:133.12,
img:<i className="fas fa-images fa-2x"></i>,
location:<i className="fas fa-map-marked-alt fa-2x"></i>,
edit:<i class="fas fa-edit fa-2x"></i>             
      },
      {fmr: "" ,
      mou:" ",
      bgoi:"-",
      bea:"167.06",
      uc:"Yes",
      pp:30,
      start:"March-19",
      complete:"April-20",
      eacomplete:"Nov-21",
      ho:"",
remark:"Slab 1st & 2nd Floor casted. Work is in progress",
        serial:8,
name:"MO Transit Hostel 12 units, DH Gopeshwar",
district:"Chamoli",
executing:"Pey Jal Nigam",
sanctioned:"2018-19 approved amt 4162",
cost:344.99,
goi:344.99,
released:177.93,
expenditure:63.51,
img:<i className="fas fa-images fa-2x"></i>,
location:<i className="fas fa-map-marked-alt fa-2x"></i>,
edit:<i class="fas fa-edit fa-2x"></i>             
      },
      {fmr: "" ,
      mou:" ",
      bgoi:"-",
      bea:"",
      uc:"Yes",
      pp:95,
      start:"March-19",
      complete:"April-20",
      eacomplete:"June-21",
      ho:"",
remark:"Finishing work is in progress",
        serial:7,
name:"MO Transit Hostel 8 units,CHC Ghat",
district:"Chamoli",
executing:"Pey Jal Nigam",
sanctioned:"2018-19 approved amt 4162",
cost:233.38,
goi:233.38,
released:233.38,
expenditure:188.224,
img:<i className="fas fa-images fa-2x"></i>,
location:<i className="fas fa-map-marked-alt fa-2x"></i>,
edit:<i class="fas fa-edit fa-2x"></i>             
      },
      {fmr: "" ,
      mou:" ",
      bgoi:"-",
      bea:"",
      uc:"Yes",
      pp:98,
      start:"March-19",
      complete:"April-20",
      eacomplete:"March-21",
      ho:"",
remark:"Only Furniture Procurement remaining",
        serial:6,
name:"MO Transit Hostel 8 units, CHC Gaucher",
district:"Chamoli",
executing:"Pey Jal Nigam",
sanctioned:"2018-19 approved amt 4162",
cost:262.17,
goi:262.17,
released:262.17,
expenditure:240.50,
img:<i className="fas fa-images fa-2x"></i>,
location:<i className="fas fa-map-marked-alt fa-2x"></i>,
edit:<i class="fas fa-edit fa-2x"></i>             
      },
      {fmr: "" ,
      mou:" ",
      bgoi:"-",
      bea:114.32,
      uc:"Yes",
      pp:50,
      start:"March-19",
      complete:"April-20",
      eacomplete:"March-22",
      ho:"",
remark:"Location now changed Bageshwar  to SULT.  GF & FF work is in progress",
        serial:5,
name:"MO Transit Hostel 12 units, CHC sult",
district:"Almora",
executing:"Pey Jal Nigam",
sanctioned:"2018-19 approved amt 4162",
cost:319.83,
goi:319.83,
released:205.28,
expenditure:90.96,
img:<i className="fas fa-images fa-2x"></i>,
location:<i className="fas fa-map-marked-alt fa-2x"></i>,
edit:<i class="fas fa-edit fa-2x"></i>             
      },
      {fmr: "" ,
      mou:" ",
      bgoi:"-",
      bea:"-",
      uc:"Yes",
      pp:85,
      start:"June-19",
      complete:"April-20",
      eacomplete:"March-21",
      ho:"",
remark:"Electrical, & finishing work is in progress  ",
        serial:4,
name:"MO Transit Hostel 8 units, CHC Dwarahat",
district:"Almora",
executing:"Pey Jal Nigam",
sanctioned:"2018-19 approved amt 4162",
cost:242.27,
goi:242.27,
released:242.27,
expenditure:210.92,
img:<i className="fas fa-images fa-2x"></i>,
location:<i className="fas fa-map-marked-alt fa-2x"></i>,
edit:<i class="fas fa-edit fa-2x"></i>             
      },
      {fmr: "" ,
      mou:" ",
      bgoi:"-",
      bea:"-",
      uc:"Yes",
      pp:90,
      start:"June-19",
      complete:"April-20",
      eacomplete:"March-21",
      ho:"",
remark:"Finishing work is in progress",
        serial:3,
name:"MO Transit Hostel 8 units, CHC Chaukhutia",
district:"Almora",
executing:"Pey Jal Nigam",
sanctioned:"2018-19 approved amt 4162",
cost:242.11,
goi:242.11,
released:242.11,
expenditure:201.00,
img:<i className="fas fa-images fa-2x"></i>,
location:<i className="fas fa-map-marked-alt fa-2x"></i>,
edit:<i class="fas fa-edit fa-2x"></i>             
      },
      {fmr: "" ,
        mou:" ",
        bgoi:"-",
        bea:"-",
        uc:"Yes",
        pp:100,
        start:"June-19",
        complete:"April-20",
        eacomplete:"March-21",
        ho:"Yes",
remark:"",
        serial:2,
name:"MO Transit Hostel 8 units, SDH Ranikhet",
district:"Almora",
executing:"Pey Jal Nigam",
sanctioned:"2018-19 approved amt 4162",
cost:242.78,
goi:242.78,
released:242.78,
expenditure:210.05,
img:<a onClick={() => setModalShow1(true)}><i className="fas fa-images fa-2x"></i></a> ,
location:<i className="fas fa-map-marked-alt fa-2x"></i>,
edit:<i class="fas fa-edit fa-2x"></i>             
      },
      {fmr: "", 
        mou:"",
        bgoi:"-",
bea:"-",
uc:"Yes",
pp:100,
start:"March-19",
complete:"April-20",
eacomplete:"March-21",
ho:"Yes",
remark:"",
        serial:1,
name:"MO Transit Hostel 8 units, CHC Dhauladevi",
district:"Almora",
executing:"Pey Jal Nigam",
sanctioned:"2018-19 approved amt 4162",
cost:242.86,
goi:242.86,
released:242.86,
expenditure:229.952,
img:<i className="fas fa-images fa-2x"></i>,
location:<i className="fas fa-map-marked-alt fa-2x"></i>,
edit:<i class="fas fa-edit fa-2x"></i>             
      },
     
    ]
  };

  return (
          <>
    <MDBDataTable scrollY responsive
      striped
      bordered
      small
      data={data}
     
    />
   <MyVerticallyCenteredModal1
show={modalShow1} 
onHide={() => setModalShow1(false)}/>  
    </>
  );
}

export default DatatablePage;

